'use strict';

const SUPPORTED_SERVICE_LEVELS = ['STANDARD', 'EXPRESS', 'PRIORITY', 'ECONOMY', 'SAME_DAY'];
const SUPPORTED_SHIPMENT_TYPES = ['DOMESTIC', 'INTERNATIONAL'];
const SUPPORTED_TRANSPORT_MODES = ['AIR', 'SEA', 'ROAD', 'RAIL'];
const SUPPORTED_PARTNER_TIERS = ['STANDARD', 'PREFERRED', 'ENTERPRISE'];
const SUPPORTED_ROLES = ['ADMIN', 'FINANCE', 'OPS', 'PARTNER', 'BUYER', 'SELLER'];
const SUPPORTED_COURIERS = ['DHL', 'FEDEX', 'UPS', 'BLUEDART', 'ARAMEX', 'SHIPMENT_EXPRESS'];
const PRICING_VISIBILITY_ROLES = ['ADMIN', 'FINANCE', 'OPS', 'PARTNER'];

module.exports = {
  SUPPORTED_SERVICE_LEVELS,
  SUPPORTED_SHIPMENT_TYPES,
  SUPPORTED_TRANSPORT_MODES,
  SUPPORTED_PARTNER_TIERS,
  SUPPORTED_ROLES,
  SUPPORTED_COURIERS,
  PRICING_VISIBILITY_ROLES,
};