import { WORKFLOW_STATES, TERMINAL_WORKFLOW_STATES } from './workflowStates.js';

export const EVENT_TYPES = Object.freeze({
  WORKFLOW_CREATED: 'WORKFLOW_CREATED',
  ANALYSIS_COMPLETED: 'ANALYSIS_COMPLETED',
  PLAN_CREATED: 'PLAN_CREATED',
  WORKFLOW_APPROVED: 'WORKFLOW_APPROVED',
  EXECUTION_READY: 'EXECUTION_READY',
  OUTREACH_STARTED: 'OUTREACH_STARTED',
  SUPPLIER_RESPONSE_RECEIVED: 'SUPPLIER_RESPONSE_RECEIVED',
  NEGOTIATION_STARTED: 'NEGOTIATION_STARTED',
  DOCUMENTS_SUBMITTED: 'DOCUMENTS_SUBMITTED',
  DECISION_SUPPORT_REQUESTED: 'DECISION_SUPPORT_REQUESTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_FAILED: 'WORKFLOW_FAILED',
  WORKFLOW_CANCELLED: 'WORKFLOW_CANCELLED',
});

export const TRANSITIONS = Object.freeze({
  [WORKFLOW_STATES.CREATED]: {
    [EVENT_TYPES.WORKFLOW_CREATED]: WORKFLOW_STATES.ANALYZING,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.ANALYZING]: {
    [EVENT_TYPES.ANALYSIS_COMPLETED]: WORKFLOW_STATES.PLAN_READY,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.PLAN_READY]: {
    [EVENT_TYPES.WORKFLOW_APPROVED]: WORKFLOW_STATES.APPROVED,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.APPROVED]: {
    [EVENT_TYPES.EXECUTION_READY]: WORKFLOW_STATES.READY_TO_EXECUTE,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.READY_TO_EXECUTE]: {
    [EVENT_TYPES.OUTREACH_STARTED]: WORKFLOW_STATES.OUTREACH_ACTIVE,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.OUTREACH_ACTIVE]: {
    [EVENT_TYPES.SUPPLIER_RESPONSE_RECEIVED]: WORKFLOW_STATES.AWAITING_SUPPLIER,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.AWAITING_SUPPLIER]: {
    [EVENT_TYPES.NEGOTIATION_STARTED]: WORKFLOW_STATES.NEGOTIATING,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.NEGOTIATING]: {
    [EVENT_TYPES.DOCUMENTS_SUBMITTED]: WORKFLOW_STATES.DOCUMENT_REVIEW,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.DOCUMENT_REVIEW]: {
    [EVENT_TYPES.DECISION_SUPPORT_REQUESTED]: WORKFLOW_STATES.DECISION_SUPPORT,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
  [WORKFLOW_STATES.DECISION_SUPPORT]: {
    [EVENT_TYPES.WORKFLOW_COMPLETED]: WORKFLOW_STATES.COMPLETED,
    [EVENT_TYPES.WORKFLOW_FAILED]: WORKFLOW_STATES.FAILED,
    [EVENT_TYPES.WORKFLOW_CANCELLED]: WORKFLOW_STATES.CANCELLED,
  },
});

export function getNextState(currentState, eventType) {
  const stateTransitions = TRANSITIONS[currentState];

  if (!stateTransitions) {
    throw new Error(`No transitions found for current state: ${currentState}`);
  }

  const nextState = stateTransitions[eventType];

  if (!nextState) {
    throw new Error(`Invalid transition: ${currentState} -> ${eventType}`);
  }

  return nextState;
}

export function isValidTransition(currentState, eventType) {
  if (TERMINAL_WORKFLOW_STATES.includes(currentState)) {
    return false;
  }

  return Boolean(TRANSITIONS[currentState] && TRANSITIONS[currentState][eventType]);
}