export const WORKFLOW_STATES = Object.freeze({
    CREATED: 'CREATED',
    ANALYZING: 'ANALYZING',
    PLAN_READY: 'PLAN_READY',
    APPROVED: 'APPROVED',
    READY_TO_EXECUTE: 'READY_TO_EXECUTE',
    OUTREACH_ACTIVE: 'OUTREACH_ACTIVE',
    AWAITING_SUPPLIER: 'AWAITING_SUPPLIER',
    NEGOTIATING: 'NEGOTIATING',
    DOCUMENT_REVIEW: 'DOCUMENT_REVIEW',
    DECISION_SUPPORT: 'DECISION_SUPPORT',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
  });
  
  export const TERMINAL_WORKFLOW_STATES = Object.freeze([
    WORKFLOW_STATES.COMPLETED,
    WORKFLOW_STATES.FAILED,
  ]);